### ISSUE TITLE
Cultivation breaks people's internet settings

### ISSUE THREAD

**Issue by akatatsu27** [Grasscutters/Cultivation#102]
I, and many people in the #support section of the discord server have had issues with cultivation completely breaking the system's internet settings. I have observed this issue in both win7 and win11 systems, so the issue lies solely with cultivation's use of the windows API and shutdown procedure. As the average user can't be expected to effectively troubleshoot network settings, this issue should be addressed *immediately*, to prevent further people from breaking their computers. This is a severe error, and until cultivation is fixed, its use should be *discouraged*.

**Comment by SpikeHD** [comment]
"Breaking peoples internet settings" is very vague, I don't know what that means nor the actual problem. The only network related changes Cultivation makes are those related to the proxy settings, of which the fix is as simple as disabling the proxy in Windows settings itself.

If there is some far more nefarious issue that has somehow never arisen until now though, please describe it in a way I can actually look into and debug.

**Comment by akatatsu27** [comment]
> "Breaking peoples internet settings" is very vague, I don't know what that means nor the actual problem. The only network related changes Cultivation makes are those related to the proxy settings, of which the fix is as simple as disabling the proxy in Windows settings itself.
> 
> If there is some far more nefarious issue that has somehow never arisen until now though, please describe it in a way I can actually look into and debug. Thank u :)

I have no idea what can cause this, but disabling the proxy sometimes doesn't work. Here's a relevant topic:
https://discord.com/channels/965284035985305680/1033357014283341845

**Comment by Birdulon** [comment]
>and the internet might mysteriously only work when cultivation is running.

Yes, that would happen when the system proxy settings are pointed at mitmproxy.

A lot of this just comes down to global state, the only clean solution that wouldn't suffer from this would be forcing proxy settings onto the game process itself, e.g. by something like https://sourceforge.net/projects/injectsocks

**Comment by thecutefinder** [comment]
Automatically terminating the proxy may be a good idea, but isn't it supposed to already do this? I've never had the same proxy error, and I use Cultivation all the time.

**Comment by Birdulon** [comment]
>isn't it supposed to already do this?

Yes, the launcher is supposed to kill the proxy process and revert the Windows global proxy settings when it is closed. It can't do the latter if it is force-killed or if, say, the computer is switched off suddenly. That last detail makes it impossible to idiot-proof it while using Windows global proxy settings.

**Comment by thecutefinder** [comment]
This reminds me of the quote "A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools."

**Comment by jimkage** [comment]
How do you fix this crap ? even though I managed to revert it (got internet working back ) my windows news feed is down. Holy shit.

**Comment by thecutefinder** [comment]
Join the Discord server and read the pinned list of common issues, which tells you how to fix it and prevent it from happening again.

**Comment by akatatsu27** [comment]
The obvious solution I learnt from my hentai games is to NOT spawn a console terminal. The `X` button immediately kills the process, as it would if you killed the process from the windows task manager. Termination signals can be sent from GUIs.
You can't expect users to not press the big red termination button, which they do with every other "normal" app.

**Comment by thecutefinder** [comment]
The red X button _does_ kill the proxy.

**Comment by SpikeHD** [comment]
> The obvious solution I learnt from my hentai games is to NOT spawn a console terminal.
Haha dw, we don't distribute debug builds with the console anymore

**Comment by thecutefinder** [comment]
Fixed in https://github.com/Grasscutters/Cultivation/commit/302754d486da97a88a71a055711b2d2aaa05c6c3
