### ISSUE TITLE
Grasscutter.zip error not downloading

### ISSUE THREAD

**Issue by Pcackplays2** [Grasscutters/Cultivation#104]
I click download on either stable or latest and all the files download except grasscutter.zip which says error each time
![image_2022-10-25_204647912](https://user-images.githubusercontent.com/85414016/197834032-c620794b-7bbd-4035-8b7c-1b5ca8c88df5.png)
![image_2022-10-25_204708212](https://user-images.githubusercontent.com/85414016/197834110-bcd1ed34-f748-4bfd-a4ae-50bd77585be6.png)

**Comment by Drevoed** [comment]
Read the second line.

**Comment by SpikeHD** [comment]
Many fixes have been merged since then, so this should be less of a problem. Never be afraid to restart the download 👍
