### ISSUE TITLE
system error always appears when launching game

### ISSUE THREAD

**Issue by coolbgaming** [Grasscutters/Cultivation#127]
how to fix

**Comment by NotThorny** [comment]
This is not an issue with Cultivation itself but rather an issue with Grasscutter configuration differing via Cultivation than other proxies. You have to change your grasscutter configuration settings, and should seek out the [Grasscutter discord](https://discord.gg/grasscutter) for support. Many issues including this one are answered in the pinned thread in #support there.

**Comment by jimkage** [comment]
Theres nothing on the discord though just a bunch of weirdos, I really don't want to have to ask someone else like a faggot to get attention for help. Holy fuck what a pain in the ass.
