### ISSUE TITLE
3dmigoto not working

### ISSUE THREAD

**Issue by DiveButNoShatter** [Grasscutters/Cultivation#133]
when i launch with cultivation 3dmigoto just doesnt work when i have it checked but when i launch normal genshin with 3dmigoto it works and i made sure to do the proper steps for launching 3dmigoto with cultivation and i tried used both versions of 3dmigoto(Playing mods and development) but it wont work when i launch with cultivation would there be a way to fix this

**Comment by NotThorny** [comment]
Are you sure you're launching from the + menu with 3dmigoto checked? If you aren't seeing the 3dmigoto loader open before the game, you're not launching with it. You could also simply launch the 3dmigoto loader before launching the game from Cultivation.

**Comment by Gustavoalmeidavidal** [comment]
The same thing is happening to me, I ended up here looking for a solution. I even opened 3dmigoto launcher directly as you said, the log is as follows:

"d3d11.dll description: "3Dmigoto - d3d11.dll"
3DMigoto Version 1.3.16
Loaded E:\.3dmigoto\d3d11.dll

3DMigoto ready - Now run the game.
Target process found (4480): D:\Genshin Impact\Genshin Impact game\GenshinImpact.exe" 

But it does not actually works with cultivation.

**Comment by Gustavoalmeidavidal** [comment]
This actually solved it, thank you!

**Comment by Radiyooooo** [comment]
yo, so I'm new to modding and I got some questions on how to use 3dmigoto AND how to use HSRGameStarter, if anyone can help me, pls help on how to do it step by step, because my W11 loader on my 3dmigoto ain't popping up

**Comment by SpikeHD** [comment]
Never heard of HSRGameStarter (you are in a repo for a Genshin launcher, just so you know :P), but you can (and should) post your problems to the [GI-Model-Importer](https://github.com/SilentNightSound/GI-Model-Importer) Github instead. The same channel with the video of setting up Cultivation also has a video for setting up mods for the game.

**Comment by Rimuti** [comment]
I did everything correctly as I saw in the videos and even checked on the page, but whenever I open the game it not only takes a long time to load but also crashes whenever the world is about to open and returns to the launcher screen. How do I resolve this? Is it something in the game? In the program? In mods? On the computer? I do not know what else to do...

**Comment by ksjkddkk** [comment]
![image](https://github.com/Grasscutters/Cultivation/assets/170717086/810de2d6-07fa-47dc-8a07-2edf1679687a)
oh gosh,i can't find my W11Loader.exe,I'm a noob for using computer

**Comment by JackMuffin** [comment]
For some unknown reason, 3dmigoto abruptly stopped working, the console opens and closes as usual when the game starts, but for some reason there is no sign in the corner of the screen that the program is running. What could have happened to the program and how to fix it?
