### ISSUE TITLE
Kill MongoDB in some circumstances

### ISSUE THREAD

**Issue by thecutefinder** [Grasscutters/Cultivation#139]
Related to support post 1089738961049624648, forwarded to me by smileoflove:

> Could work like this:
> 1. You press the button to start Grasscutter via Cultivation
> 2. Cultivation looks for MongoDB service
> 3. If MongoDB exists, Cultivation starts it if it's not running. If it doesn't exist, it makes the user install it.
> 4. Cultivation starts Grasscutter
> 
> Then Grasscutter kills MongoDB on exit, but only if it wasn't already running when Grasscutter started (Cultivation will detect if MongoDB was running and can feed that to GC). 
> 
> Would fix the MongoTimeoutException posts (probably)

**Comment by thecutefinder** [comment]
(To be clear, `1089738961049624648` is a Discord snowflake ID)

**Comment by NotThorny** [comment]
I've added this in my fork for now, only works on windows though. https://github.com/NotThorny/Cultivation/commit/f4a08f229dbdfe9f237a6b87ecaec8335770b017

Some small things that may need to be ironed out: starts the service when you start Grasscutter, and stops it when you close the game - so cases can occur where the service is stopped but then the game is reopened without restarting Grasscutter (and thus the service).
