### ISSUE TITLE
cultivation wont open

### ISSUE THREAD

**Issue by BazzyGazz** [Grasscutters/Cultivation#141]
i have the msi but when i run it (with adim) it pops up the console window then closes and does nothing 
its my first time trying this stuff so please help

**Comment by KingRainbow44** [comment]
have you tried installing Microsoft Edge WebView2?

**Comment by HajosBotond** [comment]
Hello. I have the same issue, and I have the microsoft edge webview 2 and it still doesn't work.

**Comment by SpikeHD** [comment]
Install [WebView2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/)
