### ISSUE TITLE
Cultivation unable to unzip 7zip files 

### ISSUE THREAD

**Issue by Nixeld** [Grasscutters/Cultivation#145]
Cultivation version v1.0.22

Cultivation is not able to extract 7zip files downloaded from the built in mod browser from GameBanana.

```
Is rar file? false
Failed to extract zip file: invalid Zip archive
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArchive("Could not find central directory end")', src\unzip.rs:79:46
```
![image](https://user-images.githubusercontent.com/18643932/230629436-2a38ced4-d913-4c2d-b9d5-f211a238bc8f.png)

7zip file is not extracted.

**Comment by NotThorny** [comment]
If you don't want to wait on the PR you can use the release from my fork which has this applied: https://github.com/NotThorny/Cultivation/releases
