### ISSUE TITLE
Crashing Immediately (even when opened as admin)

### ISSUE THREAD

**Issue by SpikeHD** [Grasscutters/Cultivation#18]
Just leaving this for myself, some people still crash immediately when launching even as admin. Going to ask them to run the program via Command Prompt to see what the issue is

**Comment by Seeker14491** [comment]
They don't need to build from source; we can just provide them a debug build. But I think ideally the app would write a log file were error info could be written to.

**Comment by SpikeHD** [comment]
@Seeker14491  Well I had thought that too, but afaik the current release IS a debug build, and given the insta-crash, there is not a lot to learn from it

**Comment by Seeker14491** [comment]
It's not; the debug build lets you see the console output if you run it from the terminal, which the current release doesn't. Also the debug build is ~30MB while the current release is ~15MB.

**Comment by SpikeHD** [comment]
Ah, I understand, tyvm for the clarification (Magix makes the builds, I don't, so I don't have as much familiarity :P)

**Comment by SpikeHD** [comment]
Fixed in most recent build afaik
