### ISSUE TITLE
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### ISSUE THREAD

**Issue by Gianni0177** [Grasscutters/Cultivation#19]
I keep getting this error...
![Immagine 2022-07-09 141936](https://user-images.githubusercontent.com/74237570/178105502-cf312dad-b067-4b0e-b311-62fcb62198eb.png)

**Comment by Seeker14491** [comment]
Did you run it as administrator?

**Comment by SpikeHD** [comment]
This was fixed in the most recent build
