### ISSUE TITLE
Is it possible to start 3DMigoto while booting?

### ISSUE THREAD

**Issue by CCCloudFlare** [Grasscutters/Cultivation#190]
When I play a private server locally, isn't it all for the Discord mod? , so I need to open the game after opening 3DMigoto, I think this is very inconvenient, can I request an option to load this mod injector first?

**Comment by CCCloudFlare** [comment]
Or if you can teach me how to compile this kind of file, I would be very grateful

**Comment by NotThorny** [comment]
This already is an option, you need to enable swag mode from the hidden ? in the center of the title bar. Clicking on it 3 times will show mod options in settings. Set your 3dmigoto and use the + button to launch.
You can refer to the modding with Cultivation video: https://www.youtube.com/watch?v=E6hZZU2AQB4&t=81s
You can also scroll the release notes back to when it was added, which has the info on how to enable it.

**Comment by CCCloudFlare** [comment]
Wow, that's right, thank you very much, I'm glad I don't have to go through so many tedious steps when launching the game

**Comment by gptlang** [comment]
Why are the videos now private?

**Comment by NotThorny** [comment]
> Why are the videos now private?

Spike, the uploader, probably didn't want to have them on his channel since he is not an active member of the GC/Cultivation community any longer, and the videos have been targeted by Hoyo before silly reasons.

It's very straightforward as I already explained how to do in the same message that links the video.

**Comment by gptlang** [comment]
I've got most things working. Was just out of curiosity. fwiw the video is still on the internet archive.
