### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by WenBing2078** [Grasscutters/Cultivation#196]
It seems that windows really hates this program, every three or five days windows deletes the program and then I have to reinstall it and click on "Allow to remain on machine" to use cultivation.
![屏幕截图 2023-08-29 232626](https://github.com/Grasscutters/Cultivation/assets/109894308/4ac6dcbc-177e-430f-8bfa-046c49d09e2a)
![屏幕截图 2023-08-29 233519](https://github.com/Grasscutters/Cultivation/assets/109894308/f172d08b-93d5-42ae-97be-4a9f015f4e55)

**Comment by NotThorny** [comment]
![firefox_UWSwTNW2sn](https://github.com/Grasscutters/Cultivation/assets/107363768/93765b5f-400a-4ba5-876e-1ba5c4977ead)

Should be resolved here very soon, may need to do as listed here and update your definitions.
