### ISSUE TITLE
Blank

### ISSUE THREAD

**Issue by NobleEason** [Grasscutters/Cultivation#207]

**Comment by NobleEason** [comment]
![Uploading 屏幕截图 2023-10-09 153445.png…]()

**Comment by NotThorny** [comment]
Looks like your image didn't get uploaded, if you could upload it again that would be great.

**Comment by Saltman155** [comment]
The same problem occurred in my system Ubuntu 22.04. The program was blank after startup.
You can refer to this issue: https://github.com/tauri-apps/tauri/issues/5143  
The solution is to set the environment variable WEBKIT_DISABLE_COMPOSITING_MODE=1 in your system
