### ISSUE TITLE
[Feature Request] Automatically Sync

### ISSUE THREAD

**Issue by a-w-a-y** [Grasscutters/Cultivation#212]
It would be nice if Cultivation could automatically sync with data from official Genshin servers, or at least showcased servers so maybe we could try out builds with new characters that we want to pull for

**Comment by NotThorny** [comment]
Cultivation is just a launcher, it sounds like you're asking for something related to the server-side like Enka plugin (public showcase copying). 

There also is absolutely no way to auto sync official data as neither Grasscutter nor Cultivation have such access to official databases or data. Using InventoryKamera or other 3rd party scanning tools on your own PC, or Enka GC plugin for public showcase only is the closest you will get.

Either way, that's something to do be done on your server-side (Grasscutter), not on Cultivation which is just a launcher.
