### ISSUE TITLE
4214 error + discord invite not working 

### ISSUE THREAD

**Issue by saitheseamilk** [Grasscutters/Cultivation#214]
Whenever I open cultivation, I log in, I've already have gotten a 502 error, but figured out how to fix it. But now I am getting 4214 error. Just like I did with the last error I looked to see if anyone has fixed this and what they did. But all I got was you need to go to the discord support. Like a person with a brain, I did that, but the invitation was invalid and I can't get to the discord, can someone please just tell me how to fix it from here. This is starting to get repetitive where I'm searching for every discord link on here and trying it out.

**Comment by KingRainbow44** [comment]
https://grasscutter.io/discord
