### ISSUE TITLE
Cultivation crashes when run as Administrator under limited account.

### ISSUE THREAD

**Issue by DonBureq** [Grasscutters/Cultivation#216]
Hello,

The launcher fails to load showing the error when it is launched under limited account as administrator. I am assuming after starting the launcher as administrator, program removes its permissions and then tries to write to the administrator profile's directory. please fix the issue.

Steps to reproduce:

1. create Limited account 
2.Run the launcher under limited account as Administrator

![image](https://github.com/Grasscutters/Cultivation/assets/112818768/d524b5f3-6bbb-469d-acf5-f72edf0d8f3e)
"xdd" is the administrator account directory

**Comment by KingRainbow44** [comment]
this might be a microsoft edge thing? not sure 100%

**Comment by NotThorny** [comment]
In a case like this, make the folder yourself and then webview can access it.
