### ISSUE TITLE
Black screen on X11

### ISSUE THREAD

**Issue by fedetrifo06** [Grasscutters/Cultivation#220]
Cultivation on Fedora with X11 show a grey screen, but on Wayland it works normally.

**Comment by fedetrifo06** [comment]
Yes, for me is working fine on both Wayland and Xorg (for the black screen I simply remember where the buttons are, lol)...
Have you installed aagl?

**Comment by Versitorix** [comment]
I've had this problem too. Running the launcher via command line revealed a `AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer` error. It seems to be a known issue with webkit2gtk: https://github.com/tauri-apps/tauri/issues/9304.
Try running it as `WEBKIT_DISABLE_DMABUF_RENDERER=1 ./cultivation` and if it works make it permanent by doing what https://github.com/tauri-apps/tauri/issues/9304#issuecomment-2028409103 suggests.
