### ISSUE TITLE
java is not recognized as an internal or external

### ISSUE THREAD

**Issue by meltinn** [Grasscutters/Cultivation#228]
i'm having this problem when i try to click on the button next to the launch one? can someone help me on what i need to do? :)

**Comment by NotThorny** [comment]
Java 17 is required to run Grasscutter. You should see the quick setup guide for Grasscutter to have the full setup instructions for running a local server.
https://github.com/Grasscutters/Grasscutter?tab=readme-ov-file#quick-setup-guide
