### ISSUE TITLE
Support multiple deployments

### ISSUE THREAD

**Issue by cel-ti** [Grasscutters/Cultivation#229]
Any possibility to inherently support multiple instances

**Comment by NotThorny** [comment]
Of Cultivation or of the game? Both already should be.

**Comment by cel-ti** [comment]
Of Cultivation, im not aware if theres a switch button in the gui

**Comment by NotThorny** [comment]
Ah I see, you mean like multiple profiles. There is no handling for having multiple profiles in Cultivation currently, but there is a way to have several with a little manual work.

The configuration file `configuration.json` is in `%appdata%\cultivation`. You can rename configuration.json to something else, and then run Cultivation again. It will generate a new configuration file, which you can then change to be your alternate setup.
Then you can switch between them through renaming the files. Only the one named `configuration.json` will be loaded, and you can press F5 in Cultivation to reload.

While it takes a little renaming each time you want to switch, it may still be faster than changing all your settings if you have significantly different ones between each config.

This can just be a temporary solution. I'll look at making a little profile switching system, but no guarantees on a timeline for that.
