### ISSUE TITLE
[Docs] Invalid URL

### ISSUE THREAD

**Issue by lunatic-gh** [Grasscutters/Cultivation#232]
Due to discord now having url's expire (afaik after not being requested for some time), the url at https://github.com/Grasscutters/Cultivation/blob/main/THEMES.md for the example theme is invalid/expired.

It should probably just be uploaded to github or another site instead, where it doesn't expire.

**Comment by NotThorny** [comment]
Discord urls now expire after 24hrs as far as I'm aware, but themes (including the example) are all still in the Grasscutter discord in the themes channel.

**Comment by NotThorny** [comment]
Fixed in dcc2b1707
