### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Tia0510** [Grasscutters/Cultivation#233]
After pressing 'Launch,' the game crashes immediately after the word 'Hoyoverse' appears. I tried compatibility mode, but it didn't work. Is there a solution?

**Comment by NotThorny** [comment]
What game version do you have?

**Comment by MorishimaKureo** [comment]
i have the same problem i just updated my genshin to 5.1

**Comment by NotThorny** [comment]
5.1 is not a supported version, it will not work.

**Comment by NotThorny** [comment]
As per the client patching notice in the readme, it starts at version 3.1 and ends at the latest official Grasscutter version - 4.0. If you want newer versions than that then you need to use a newer version of Cultivation, such as https://github.com/NotThorny/Cultivation

**Comment by Tia0510** [comment]
i was running it on 5.1 without realizing it
It was done in 5.0. thank you

**Comment by NotThorny** [comment]
5.0 patching will be supported in the next release as the newer version is merged.
