### ISSUE TITLE
"could not patch! You're trying to launch a version that you dont have a patch for!

### ISSUE THREAD

**Issue by jakeal112233** [Grasscutters/Cultivation#236]
i looked in the patches folder and there is no 5.1 patch. can someone tell me how to fix this or how to revert my game version back to 5.0 so i can play.

![Screenshot 2024-10-31 112746](https://github.com/user-attachments/assets/2c2aebfb-678b-4042-a057-8ab02194c412)
![Screenshot 2024-10-31 112409](https://github.com/user-attachments/assets/07dee4e4-7937-45da-a5f5-31c219adab07)

**Comment by NotThorny** [comment]
As it says there, if getting patches means nothing to you then you have the wrong game version, you must get 5.0 or earlier.

Download 5.0 from the archive repo same as any other version.
https://github.com/JRSKelvin/GenshinRepository/blob/main/Version%205.0.0.md

**Comment by jakeal112233** [comment]
@NotThorny do you happen to know where there is any tutorial for how to do it. i have no clue what im doing

**Comment by NotThorny** [comment]
There are more tutorials than you can possibly count, but I would suggest you go follow the setup for Grasscutter.
https://github.com/Grasscutters/Grasscutter?tab=readme-ov-file#quick-setup-guide

**Comment by jakeal112233** [comment]
@NotThorny I'm confused. I don't see where it says how to download older versions...

**Comment by NotThorny** [comment]
The first link I sent was to the archive, to the exact version you wanted. The second link is to the setup guide which also links you to the same repository but for a different version. If you need help with that, please go to the Grasscutters discord.

**Comment by NotThorny** [comment]
Also since you're trying to play on YuukiPS, you can see the same links on the YuukiPS website, with the same steps on how to get it. https://ps.yuuki.me/game/genshin-impact
You can also go to the [YuukiPS discord](https://www.discord.gg/yuukips) if you need help specifically with Yuuki
