### ISSUE TITLE
Not support game version 5.X 

### ISSUE THREAD

**Issue by pokemonfan63** [Grasscutters/Cultivation#247]
![image](https://github.com/user-attachments/assets/856e735f-9583-48be-8148-fba30be47e3e)
It seems that the grasscutter50 only support 5.0, not support 5.2.

**Comment by NotThorny** [comment]
That is correct, the 5.0 AIO only supports game version 5.0. If you want a different version server, you will need to download and set it. I provide a 5.2 build from UnknownAnimeGamePS on my releases: https://github.com/NotThorny/Grasscutter/releases/download/culti-aio/UnknownAnimeGamePS52.zip
