### ISSUE TITLE
Um, where's the proxy?

### ISSUE THREAD

**Issue by AZthemute** [Grasscutters/Cultivation#25]
After downloading the newest release and starting the game on Grasscutter, the proxy just... doesn't start? And obviously I can't connect to the server. This isn't a problem with my game or internet connection because using Grassclipper works just fine...

Edit: The console window shows that I am connected to the proxy, but clearly I'm not because nothing works properly.

**Comment by KingRainbow44** [comment]
did you run cultivation as administrator? potentially a registry edit wasn't made

**Comment by AZthemute** [comment]
> did you run cultivation as administrator? potentially a registry edit wasn't made



> did you run cultivation as administrator? potentially a registry edit wasn't made

When I installed and ran Cultivation, it asked to install a certificate, which I did. Nothing happened.
![image](https://user-images.githubusercontent.com/104761702/178564726-aedb79b9-bc14-47b2-b4d0-eb2bb9588554.png)
This is all the console shows.

**Comment by SpikeHD** [comment]
Try connecting again, and when connected, check your Windows proxy settings to see if they're set.

**Comment by AZthemute** [comment]
> Try connecting again, and when connected, check your Windows proxy settings to see if they're set.



> Try connecting again, and when connected, check your Windows proxy settings to see if they're set.

I have to decline the UAC prompt when starting the game in order for the setting to actually change.

**Comment by SpikeHD** [comment]
Oh! Super interesting, I will take a look sometime and see why that's the case

**Comment by AZthemute** [comment]
Same results in the previous version except declining the UAC prompt doesn't change my proxy settings any more. So... this probably is just my problem somehow.

**Comment by AZthemute** [comment]
Started Cultivation from source code (latest commit) and I'm still getting these problems. This... probably is just my problem, though if people understand why this is happening... I'd appreciate it

**Comment by SpikeHD** [comment]
If you could provide logs, try some debugging, see if your Windows proxy settings are being set properly upon connecting, etc. that would be super helpful in helping *me* understand :smile:

**Comment by AZthemute** [comment]
I already posted logs (if console is what you mean) earlier. They weren't for the current commit but I seem to no longer be able to run Cultivation so...

**Comment by AZthemute** [comment]
This is definitely my problem since even using Grassclipper doesn't work. For some reason the proxy server just... closes instantly. I don't know any reason for this as I've barely messed with proxy servers recently. It just... gets terminated when the game starts, and the game doesn't even start. What on earth even is happening any more...

**Comment by SpikeHD** [comment]
Haha, I can't say I know what's going on but those extra details do help. Are you running with `yarn start:dev` or just via building and then running the exe?

**Comment by AZthemute** [comment]
> Haha, I can't say I know what's going on but those extra details do help. Are you running with `yarn start:dev` or just via building and then running the exe?
> 
> If running with `yarn start:dev` are there any logs/panics/anything being logged when you try to connect and run the game?

I'm doing both.
![image](https://user-images.githubusercontent.com/104761702/179305884-cc905de3-d423-4f3e-8345-ed92a8d50629.png)
Well, this doesn't help does it? Sigh, time to build for release...

~~also I managed to find out that the proxy server being killed was related to a firewall rule I have to block the game from using my internet, weird part is that I enable the firewall rule for my 2.8 genshin and still my 2.7 genshin kills the proxy. Then I have to restart my pc~~

Okay, I managed to build debug properly:
![image](https://user-images.githubusercontent.com/104761702/179307751-bbdc1a00-f1fe-4e3a-b5aa-b691907db2d0.png)
![image](https://user-images.githubusercontent.com/104761702/179307871-36b09684-9fe4-48de-a920-95c255b33fde.png)
This is all that really happened.

**Comment by AZthemute** [comment]
I realised that 2.8 is not officially supported and my screenshot was of 2.8, so I tried 2.7.
https://cdn.discordapp.com/attachments/748188072826372299/997613885622325310/2022-07-15_22-20-17.mp4
The video best describes my issue.

**Comment by SpikeHD** [comment]
In the instance of that error, disable encryption (via Cultivation OR by setting `useEncryption` and `useInRouting` in your server config to `false`), and make sure HTTPS is off when connecting (both must be done to prevent this issue, I will likely be pushing a change to automatically disable encryption in the configuration at some point)

**Comment by AZthemute** [comment]
Feels a bit weird to not use HTTPS, but it works which is the most important part. Is this an issue that will be fixed eventually or is it impossible to fix?

**Comment by SpikeHD** [comment]
It's not an issue to not be using HTTPS, you will still need to enable it to connect to external servers anyways so there is no security implication. I mentioned before that I will be likely adding an automatic server configuration change but that is probably about the extent we'll be taking.

**Comment by AZthemute** [comment]
Alright I see, thanks for the help!
