### ISSUE TITLE
Crashes when cancelling UAC on game launch

### ISSUE THREAD

**Issue by 4Benj** [Grasscutters/Cultivation#26]
Cultivation crashes when you click ``Launch`` and hit ``No`` when UAC asks if "_CertainAnimeGame_.exe" wants to make changes to your device. 
I'm pretty sure this worked before and I've noticed that ``system_helpers::run_program`` was changed in PR #20 which was merged in with commit 0b2296f9184061e63f289115d65a9713f8fe4328. 

Debug Information:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1223, kind: Uncategorized, message: "The operation was canceled by the user." }', src\system_helpers.rs:6:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\cultivation.exe` (exit code: 101)0. Error = 0
error Command failed with exit code 4294967295.
```

**Comment by SpikeHD** [comment]
Should be fixed in [33c67ee](https://github.com/Grasscutters/Cultivation/commit/33c67eef06e4c85a07d329edadac8d6572920a35)
