### ISSUE TITLE
Cultivation keeps connecting to official server

### ISSUE THREAD

**Issue by Johnny9926** [Grasscutters/Cultivation#27]
I'm pretty sure that I followed all the steps correctly, but when I launch Genshin via Cultivation, it keeps connecting to the official server. Btw, I hosted my own local server. The command prompt works fine, I can even create an acc with it. Idk if I messed up at any part, so I really need some help

**Comment by 4Benj** [comment]
#25 -_-

**Comment by Johnny9926** [comment]
Oh sry... didn't know that it's relevant
