### ISSUE TITLE
Failed to parse response: expected value at line 1 column 1

### ISSUE THREAD

**Issue by Arxyma** [Grasscutters/Cultivation#29]
![image](https://user-images.githubusercontent.com/48849062/179170395-e12dc617-f591-4a8b-bc5e-5bd93987c103.png)
i have been reinstall but the problem still same. what should i do

**Comment by SpikeHD** [comment]
I have to assume that is just a problem with the API in getting the official game background. I assume you are still able to set a custom background? That should at least prevent you from being flashbanged when opening Cultivation :P
