### ISSUE TITLE
Genshin Impact System Error

### ISSUE THREAD

**Issue by akinooGitHub** [Grasscutters/Cultivation#36]
So I tried to open Genshin Impact on the Cultivation launcher and when I try to login it says: "System Error. Please try again later.". I've looked if I missed something in the process but seems that there's nothing that I've left:

- I've installed the Proxy certificate
- I've put the WIndows proxy settings set to manual
- I have the 2.8 client
- I unchecked HTTPS and disabled Encryption

If anyone could help I would be very grateful!

**Comment by tiramisu69** [comment]
did you make it work?
