### ISSUE TITLE
[Feature request] command line arguments

### ISSUE THREAD

**Issue by RhythmLunatic** [Grasscutters/Cultivation#44]
Since I launch genshin Impact from steam big picture, using a mouse is a hassle. So I would like command line argument support to skip the launcher's GUI and automatically start the game, such as
```
--custom_server=false --akebigc --3dmigoto
```

Maybe additional arguments like setting the path to akebi and 3dmigoto could be useful too.

And for server owners, `--use-ssl=true --connect=fakeserver.com:666` could allow connecting to a custom server of their choice and setting SSL on/off.

If `--connect` is specified then `--custom_server` would implicitly be true, if no connect argument is given while `--custom_server=true` is given then the previous server would be used like the GUI.

**Comment by Nicolas-GE** [comment]
i would like to add to this to allow genshin launch options, i play in borderless fullscreen (launching the anime game with `-popupwindow -screen-fullscreen 0`) so it would be nice to have access to launch options

**Comment by SpikeHD** [comment]
Sorry for taking so long on this lmao, it should finally be done soon ❤️
