### ISSUE TITLE
[Request] Is it possible to make localization fall back to english values if they don't exist?

### ISSUE THREAD

**Issue by Miralyn** [Grasscutters/Cultivation#45]
The question is in the title. Right now, if there are some lines in the localization files that are missing, whether due to updates or some reason, they just don't get displayed. Attaching screenshots to show what I mean.
![culti_en](https://user-images.githubusercontent.com/41351810/180741578-0e708e8f-6dbc-4971-b2e8-97f82a97033b.jpg)
![culti_ru](https://user-images.githubusercontent.com/41351810/180741591-c25b70a5-fef0-4efb-83be-a5ea73c489a7.jpg)

**Comment by SpikeHD** [comment]
It's actually supposed to but I guess it doesn't work :skull: , though most of those should actually be translated already. Oh well I will fix

**Comment by SpikeHD** [comment]
Implemented in afa40f437fd6d17f5d9b4d8feecefafd20d97bd9 and will be available ion the next release :)
