### ISSUE TITLE
cannot connected to proxy

### ISSUE THREAD

**Issue by Arxyma** [Grasscutters/Cultivation#46]
![image](https://user-images.githubusercontent.com/48849062/180788072-8954c73d-7829-4bc7-a9f5-fd168f3280e4.png)
I looked at other issues, most of them have the text connect to proxy, but why mine can't connect?

**Comment by SpikeHD** [comment]
Does your game even open? It should only ever disconnect once it's closed properly. Are your windows proxy settings set properly when connected? You can also try reinstalling the proxy certificate in settings.

**Comment by MerijnHendriks** [comment]
Also make sure you didn't click inside the console window, because then it freezes and doesn't receive requests properly.
