### ISSUE TITLE
resources issue

### ISSUE THREAD

**Issue by jackfost** [Grasscutters/Cultivation#48]
culti gets stuck at 0 bites a second for hours and when i install manually my resources I get the error in the image bellow and cannot login. if someone can help I would appreciate it. (and I downloaded 2.8 resources btw)
![Screenshot 2022-07-26 151613](https://user-images.githubusercontent.com/106411756/181093734-f440f5bf-4e01-403f-8d07-e9ebb1dd5289.png)

**Comment by SpikeHD** [comment]
Not a cultivation issue
