### ISSUE TITLE
[Feature request] Add Pre Configured Path For Different Genshin Directory

### ISSUE THREAD

**Issue by SCUMBAG0LEE** [Grasscutters/Cultivation#49]
The Ability To Add Other Genshin Version Directory And Just Switch To Em At Instance By Just Accessing A Panel Definitely Gonna Increase Quality of Life, Take Minecraft Launcher For Example XD.

**Comment by MerijnHendriks** [comment]
Not sure if newer servers (and their data) are backwards compatible with older clients. So you possibly would not only need to change the genshin client, but also the server.
