### ISSUE TITLE
Missing File Binoutput and Excelbinoutput

### ISSUE THREAD

**Issue by GenshinPrivateNotWorking** [Grasscutters/Cultivation#63]
When i try using the private server it says missing file put Binoutput and Excelbinoutput in resource folder

**Comment by SmexyFelf** [comment]
there is a wiki on this github and a discord with a faq. you do not have the resources for the game to start

**Comment by GenshinPrivateNotWorking** [comment]
oh so do i go to the discord to get the resources?
