### ISSUE TITLE
[Feature request] Automatically set 3dmigoto loader target path

### ISSUE THREAD

**Issue by MerijnHendriks** [Grasscutters/Cultivation#64]
It would be cool if cultivator could automatically set the loader target from `d3dx.ini` to the genshin directory set in the launcher. While it can be expected of people to be capable of setting the path themselves when running swag mode, I think it would a nice small addition to streamline things a bit more.

It can be implemented using [`rust-ini`](https://docs.rs/rust-ini/latest/ini) by modifying `d3dx.ini` as soon as 3dmigoto's executable path is set in the options panel.

**Comment by SpikeHD** [comment]
Donezo
