### ISSUE TITLE
[Feature request] Provide option to download tools from swag mode

### ISSUE THREAD

**Issue by MerijnHendriks** [Grasscutters/Cultivation#65]
Currently users have to download and set the paths to the various tools available in swag mode. Since all of it is hosted publicly on github (exception might be the special reshade), I think it would be nice to present the download option for those tools under the download menu when in swag mode.

It would make modding feel more intergrated with the rest of the launcher, (almost) everything needed would be in once place and would make it a bit more friendly to use those tools.

**Comment by NotThorny** [comment]
Currently added GIMI 3dmigoto and plans to add reshade a bit later (when I get to making it auto-config on download) but since the last one is a paid service and no longer on github it should be left up to the user to find and get it.
