### ISSUE TITLE
Proxy sometimes does not connect when using mods

### ISSUE THREAD

**Issue by SirDarwin** [Grasscutters/Cultivation#67]
I have been using Akebi and 3dmigoto with Cultivation (swag mode) and have had an issue whereby when launching with these mods and connecting via Grasscutter, the proxy sometimes does not connect and I get the captcha from official servers. This happens after no known settings were changed nor were any configurations with Akebi or 3dmigoto. 

[fixed]I am also experiencing an issue whereby when using Reshade, it does not inject properly and fails to connect to the proxy each time, however I'm not as sure about that issue as Reshade has not yet worked for me and it could be an error on my end. I was previously having the same issue with Akebi but discovered its launch path was pointing toward the wrong install of the game, and so Cultivation didn't connect the proxy, so since I'm new to Reshade this could also be happening there (though I did change the install path in the PowerShell script).

Update: SpikeHD pointed out that **Cultivation must be run in Administrator mode in order to use Reshade**. That issue has now been fixed.

**Comment by SpikeHD** [comment]
Reshade requires Cultivation to be run as administrator, no exceptions. The powershell script is unused and untouched by Cultivation.

**Comment by SpikeHD** [comment]
Many fixes have been implemented since this issue, so there is a likelyhood that it is now fixed 👍
