### ISSUE TITLE
Entering the teapot creates an error

### ISSUE THREAD

**Issue by keesep** [Grasscutters/Cultivation#69]
Whenever I give myself a teapot, select a realm layout and enter, the main house doesn't exist and the placement function is gone. Then, I get this error in the console and get a white screen the next time I try to enter the door into the game.
![image](https://user-images.githubusercontent.com/86033926/184802209-8eedfb49-1ab6-425c-8a97-75d83093fa95.png)

**Comment by SpikeHD** [comment]
Unrelated to Cultivation
