### ISSUE TITLE
got a sign error 

### ISSUE THREAD

**Issue by xia0ji233** [Grasscutters/Cultivation#76]
When I login in games,I got an error message “System Error,please try after a minite”。
The Server run in localhost also got an error but not crash,so I ignore it.
![image](https://user-images.githubusercontent.com/73569212/187048047-ef55e60a-913e-4213-8853-847de7fe073c.png)
When I run the client,the terminal also give me an error message.
![image](https://user-images.githubusercontent.com/73569212/187048079-028425a0-38c7-4efd-9b0a-c9333ba7fad1.png)
I will appreciate it very much if someone help me.

**Comment by SpikeHD** [comment]
A couple things:
* Your game path is not set correctly. It should be `Genshin Impact Game/GenshinImpact.exe` (or `YuanShen.exe`, though I do not know if the metadata patch will work with the CN version of the game)
* The registry setting is unrelated, and is not necessary to do
* `System Error` occurs if the proxy is not being set properly. Check your Windows settings to ensure `Manual proxy setup` is enabled

**Comment by xia0ji233** [comment]
I'm sure that the path I set is correct like this
![image](https://user-images.githubusercontent.com/73569212/187057046-ebfe17c1-68f0-47b9-8408-2b15811d4e87.png)
But the client terminal also give me an error message 
![image](https://user-images.githubusercontent.com/73569212/187057060-f2970ec5-5f57-4e16-8873-7796024d2c35.png)
I set System Proxy follow Grasscutters said,loaclhost:8080， I'm not sure it is correct.
I have tried many times but got same error message.

**Comment by SpikeHD** [comment]
Your executable is now correctly set, yes.

That is not the correct proxy address, however, as Cultivation uses a different one. I am sure it is not being set because of system languages or something.

The correct value for the address section of the proxy is “http://127.0.0.1:8035;https://127.0.0.1:8035”

**Comment by xia0ji233** [comment]
When I run server, it help me set proxy address 
![image](https://user-images.githubusercontent.com/73569212/187057485-3cb9b59a-3f19-4c7c-893c-2ff826fc70de.png)
is it correct?
Maybe I have not know about where the proxy server in and which program run as proxy server

**Comment by SpikeHD** [comment]
When using cultivation, you do not need to use the server scripts located in the Grasscutter folder. You can set your .jar file in the options, and launch it with the button next to “Launch”.

Cultivation uses its own internal proxy program as well, so if you are not using that, you probably do not even need to be using Cultivation.

If you would like an (unfortunately english-only) video on what Cultivation can do, as it can handle everything for you, you can watch it here: https://youtu.be/e0irOYbQe7I

**Comment by xia0ji233** [comment]
So if I set proxy server to my private server, I could even use official client?
But I still don't know where my proxy forwarding

**Comment by SpikeHD** [comment]
I am unsure of what you mean, but Cultivation has its own internal proxy that automatically activates and deactivates when launching/closing the game. It redirects requests made by the game to the address you specify when “Connect with Grasscutter” is enabled and you launch the game. The address I provided, and that you now have set properly, is the address of Cultivations proxy.

**Comment by xia0ji233** [comment]
OK,now I connect to my server,but when I login,I got a new error message.
![image](https://user-images.githubusercontent.com/73569212/187123901-16cadc7d-83b8-42b4-9bff-05913ed43ed3.png)

I change Hosts like https://github.com/Grasscutters/Grasscutter/wiki/Running#traffic-route-map
I don't set any proxy

**Comment by SpikeHD** [comment]
I cannot read Chinese, so I do not know what that error is. Since you are not using the Cultivation proxy, this issue is no longer relevant to Cultivation.
