### ISSUE TITLE
Cultivation doesn't open

### ISSUE THREAD

**Issue by AsrielYoutubd** [Grasscutters/Cultivation#77]
I recently got my new computer. I installed Genshin and all of that, the i installed Cultivation.zip but when i open it, it shows the CMD and closes. Any idea how to fix that?

**Comment by SpikeHD** [comment]
Don’t use the zip, or install Webview

**Comment by AsrielYoutubd** [comment]
Oh damn but can you pass me link for webview

**Comment by SpikeHD** [comment]
Google is free
