### ISSUE TITLE
Ability to set server download path

### ISSUE THREAD

**Issue by minhngoc25a** [Grasscutters/Cultivation#79]
We should be able to set the download path for Grasscutter when using Cultivation to download Grasscutter. Same for the Data and Resources file as well. I know that there is a workaround by installing Grasscutter manually, but this should be a nice quality of life for those that aren't advanced.

**Comment by Arikatsu** [comment]
Imo I just see this as an added feature. If you aren't advanced then I don't think you should be messing with stuff inside the grasscutter folder anyway. And you can basically do everything basic from the launcher itself. Cultivation was in fact meant for people that aren't advanced enough to know that stuff. So adding this people don't really gain a lot except choosing a destination. And tbh all files having the same folder structure makes it easy to give out support to them.

But I'm not against this either, just my opinion.
