### ISSUE TITLE
Dedicated server: detailed issue report on "System error. Please try again later"

### ISSUE THREAD

**Issue by UrsusArctos** [Grasscutters/Cultivation#80]
I run recent Grasscutter on a dedicated Gentoo Linux server and so far it appears to run smoothly:

Vecanoi /opt/grasscutter # /opt/openjdk-bin-17/bin/java -jar ./grasscutter-1.2.3-dev.jar
18:58:39 <WARN:Language> Failed to load language file: en-.json, falling back to: en-US.json
18:58:39 <INFO:Language> Loading cached TextMaps
18:58:39 <INFO:ResourceLoader> Loading resources...
18:58:42 <INFO:ResourceLoader> Finished loading resources.
18:58:42 <INFO:Tools> GM Handbooks generated!
18:58:42 <INFO:Grasscutter> Starting Grasscutter...
18:58:42 <INFO:Grasscutter> Game version: 3.0.0
18:58:42 <INFO:Grasscutter> Grasscutter version: 1.2.3-dev-32289e2
18:58:44 <INFO:HttpServer> [Dispatch] Dispatch server started at log-upload-os.mihoyo.com:443
18:58:44 <INFO:GameServer> Grasscutter is FREE software. If you have paid for this, you may have been scammed. Homepage: https://github.com/Grasscutters/Grasscutter
18:58:44 <INFO:GameServer> Game Server started at 2a01:xx:xx::xx:22102
18:58:44 <INFO:Grasscutter> Done! For help, type "help"

I ascertained it to be listening on both tcp/443 and udp/22102 sockets and I checked if https:// works in the browser (to that end I even obtained legit LetsEncrypt cert for it). All is OK so far.

So I then downloaded and installed latest Cultivation and ran it. The console window says:

Failed to get bg file response: missing field `bg_file` at line 1 column 318573
^ please stop reporting this as an error it's so annoying LMFAO
Starting process watcher...
Connecting to proxy...
Connected to the proxy.

That's all it ever says.
Then in Cultivation Launcher I ticked "Connect via Grasscutter" tick, entered hostname and port (443) for the dedicated server and also ticked HTTPS.
Pressed Launch.
The game said "System error. Please try again later" when I try to login (existing user in mongodb instance, any password -- this worked back with Grassclipper).

I also checked system proxy settings and yes, while Cultivation is running, the proxy host address field contains "http=127.0.0.1:8365;https=127.0.0.1:8365" and port field is empty.
This looked a little weird, so I also tried setting host to "127.0.0.1" and port to "8365" but it didn't help either.

What do I do next to make it work?

**Comment by SpikeHD** [comment]
If your proxy settings are being set correctly, first try running a local server, and if the local server runs fine then this isn't a Cultivation issue and you should consult the [Grasscutter repo](https://github.com/Grasscutters/Grasscutter)

**Comment by UrsusArctos** [comment]
I just redeployed Grasscutter locally and ran it. The server itself appears to run OK, but the game started under Cultivation keeps telling "System error. Please try again later" on login attempt.

![cultnw](https://user-images.githubusercontent.com/4576573/187183942-7ce7678e-6068-4ab9-8f89-a4f826974588.png)

**Comment by SpikeHD** [comment]
Ensure when Cultivation says it is `Connected to the proxy.` that your Windows proxy settings are being set properly. If not, ensure you are running as admin and try again, OR set your proxy settings manually to `https://127.0.0.1:8365;http://127.0.0.1:8365`

**Comment by UrsusArctos** [comment]
> Ensure when Cultivation says it is `Connected to the proxy.` that your Windows proxy settings are being set properly. If not, ensure you are running as admin and try again, OR set your proxy settings manually to `https://127.0.0.1:8365;http://127.0.0.1:8365`

Of course I made sure of that, since my very first message here mentions exactly this at the end.
Yes, the system proxy settings match what you say while Cultivation is running.
![proxy](https://user-images.githubusercontent.com/4576573/190858983-bcba4719-53a9-413a-afad-1e237582f7cf.png)
I also just now updated Grasscutter to 1.3.2, updated its resources and installed latest version of Cultivation.
Still, the game says "System error. Please try again later" every time I try to login.
What else I might be missing?

**Comment by ste94pz** [comment]
Same problem here. It works only if you disable encryption in Grasscutter and https in Cultivation.
