### ISSUE TITLE
Failed to load mono

### ISSUE THREAD

**Issue by stimulionwindowsxp** [Grasscutters/Cultivation#86]
I've gotten an issue when trying to boot up the game that reads: "Fatal Error. Failed to load mono." Not too sure what it means or what to do about it.
![Screenshot 2022-09-05 135943](https://user-images.githubusercontent.com/112897926/188498242-1ef3cdd2-ffe0-40f1-ad92-b970aff5aba3.png)

**Comment by SpikeHD** [comment]
Game issue, not Cultivation

**Comment by stimulionwindowsxp** [comment]
I see. My bad for the mistake. You guys are doing gods work, keep it up.

**Comment by stimulionwindowsxp** [comment]
By the way, I didn't clarify this correctly, but I meant booting up Cultivation, not the game executable.
