### ISSUE TITLE
Could not patch game!

### ISSUE THREAD

**Issue by Sisissizisi** [Grasscutters/Cultivation#89]
![image](https://user-images.githubusercontent.com/113131360/189208586-0eca4a33-d0bd-44fe-a099-e64b1d014128.png)

**Comment by karageee** [comment]
1.0.9 is borked, reinstall the previous version.

**Comment by MoonLGH** [comment]
its either ^ or your version is 3.0.5x because we dont patch metadata in that version

**Comment by MoonLGH** [comment]
or try running as administrator
