### ISSUE TITLE
About MongoDB

### ISSUE THREAD

**Issue by lilith-rong** [Grasscutters/Cultivation#94]
Will there be an option to start the MongoDB with the Grasscutter?
Or any option to run bat file?(Because I use a bat to start MongoDB and GrassCutter)

**Comment by SpikeHD** [comment]
MongoDB is a service that is started automatically when Windows is started, so you should never really need to open anything manually regarding it. If you have the automatic startup disabled, just open `services.msc` and start it manually.

There are no plans to support batch files.
