### ISSUE TITLE
Error 4214/Not able to connect to the server and can't delete old accounts 

### ISSUE THREAD

**Issue by Gerry014** [Grasscutters/Cultivation#99]
I uninstalled the old version of Cultivation and installed the latest to play in the private servers of Genshin Impact 3.1 but I can't delete my old accounts as before when I turn on the server, also when I try to access an already existing account I can't manage to playing because it gives me an error 4214 or says it is unable to connect to the server, I reinstalled it and restarted the computer several times but didn't get any results.

![image](https://user-images.githubusercontent.com/69633856/193459823-e10b2249-2b45-46c5-978a-fbcc36e66d57.png)

![image](https://user-images.githubusercontent.com/69633856/193460006-158eaa0c-1ec7-4a81-9ea1-1e4b43ebb698.png)

**Comment by SpikeHD** [comment]
Anything server related is unrelated to this repository.

4214 usually occurs due to no patched UA (which is not yet done by Cultivation.)

See the [Discord](https://discord.com/invite/grasscutter) for further support on common issues.
